# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97da038094e403bbd6dd3de2a902e81bf67ebaaeef53b08b4662b8da2b65036a759ed757c26fa199746bd35aa11f0cd44ff921787c2fb8b5ad8ee1a9d3596fbd

test:
  secret_key_base: cbd32474cb97b88bb8bd6fb30c2d1627f27fd237050a72e0842735b40c893d9e7e4f6ced8b6d9e0baf6e12b8ad4849557e9916854602458dead6aeb55895bb77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
